/**
 * Countries offered in the profile country picker. Rendered as an <input list>
 * datalist, so the field is a search-and-pick dropdown that ALSO accepts free text -
 * an unlisted country is still enterable, this list just makes the common ones one
 * tap away. India + the Gulf lead, since they are the academy's main regions.
 */
export const COMMON_COUNTRIES = [
  'India',
  'United Arab Emirates',
  'Saudi Arabia',
  'Qatar',
  'Kuwait',
  'Oman',
  'Bahrain',
  'Sri Lanka',
  'Pakistan',
  'Bangladesh',
  'Nepal',
  'Bhutan',
  'Maldives',
  'Afghanistan',
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'New Zealand',
  'Ireland',
  'Singapore',
  'Malaysia',
  'Indonesia',
  'Philippines',
  'Thailand',
  'Vietnam',
  'Germany',
  'France',
  'Netherlands',
  'Spain',
  'Italy',
  'Switzerland',
  'Sweden',
  'Norway',
  'Denmark',
  'Belgium',
  'Portugal',
  'Austria',
  'South Africa',
  'Kenya',
  'Nigeria',
  'Egypt',
  'Ghana',
  'Tanzania',
  'Uganda',
  'Ethiopia',
  'China',
  'Japan',
  'South Korea',
  'Hong Kong',
  'Jordan',
  'Lebanon',
  'Turkey',
  'Iraq',
  'Iran',
  'Yemen',
  'Brazil',
  'Mexico',
  'Argentina',
] as const
