#!/bin/bash

# Regenerate supabase/rebuild/0000_full_rebuild.sql from a FULLY-MIGRATED database.
#
# The rebuild snapshot is a pg_dump of the end state - it provisions a fresh DB in
# one shot. It MUST be regenerated by dumping, never hand-edited: hand-edits have
# silently drifted it before (a stale mentorships.tutor_id, a divergent persona
# scheme, a duplicate constraint that made it fail to apply at all). Run this after
# adding migrations so the one-shot file stays byte-accurate to the chain.
#
# Usage:
#   1. Point the Supabase CLI at a database that has the ENTIRE migration chain
#      applied. The simplest is a fresh local db:
#        supabase db reset      # drops + replays supabase/migrations/*.sql
#      Or link to a remote project that is fully migrated (supabase link ...).
#   2. bash scripts/rebuild-snapshot.sh    (or: npm run db:rebuild-snapshot)
#
# Requires the Supabase CLI (the same tool run-fresh-environment-test.sh uses).

set -euo pipefail

OUT="supabase/rebuild/0000_full_rebuild.sql"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

if ! command -v supabase >/dev/null 2>&1; then
  echo "Error: the Supabase CLI is not on PATH. Install it, then re-run." >&2
  exit 1
fi

echo "Dumping the public schema from the linked database..."
# Schema only (roles + data excluded) - this is a provisioning snapshot, not a backup.
supabase db dump --schema public -f "$TMP"

# Highest migration this snapshot reflects. Emitted as a machine-readable
# 0001..NNNN marker in the header so a freshness check (CI) can compare it to the
# migration chain and flag a stale snapshot. Keep the marker's format stable.
LATEST="$(ls supabase/migrations/*.sql | xargs -n1 basename | sed -E 's/_.*//' | sort | tail -1)"

{
  cat <<HEADER
-- ============================================================================
-- Cert-Ed Academia - full schema rebuild
-- ============================================================================
-- GENERATED by scripts/rebuild-snapshot.sh (supabase db dump) from the numbered
-- migrations (supabase/migrations/0001..${LATEST}) applied in order. The numbered
-- migrations are the single source of truth; this file provisions a fresh
-- database in one shot and is kept byte-identical to applying them in order.
-- DO NOT hand-edit - re-run the script instead.
--
-- Requires the Supabase-provided auth schema (auth.users, auth.uid()) and the
-- anon / authenticated / service_role roles, present on any Supabase project.
-- ============================================================================

HEADER
  cat "$TMP"
} >"$OUT"

echo "Wrote $OUT"
echo "Review the diff (git diff $OUT) and commit alongside the migrations it reflects."
