#!/bin/bash

# Regenerate supabase/rebuild/0000_full_rebuild.sql from a FULLY-MIGRATED database.
#
# The rebuild snapshot is a pg_dump of the end state - it provisions a fresh DB in
# one shot. It MUST be regenerated by dumping, never hand-edited: hand-edits have
# silently drifted it before (a stale mentorships.tutor_id, a divergent persona
# scheme, a duplicate constraint that made it fail to apply at all). Run this after
# adding migrations so the one-shot file stays byte-accurate to the chain.
#
# Usage:
#   1. Point the Supabase CLI at a database that has the ENTIRE migration chain
#      applied. The simplest is a fresh local db:
#        supabase db reset      # drops + replays supabase/migrations/*.sql
#      Or link to a remote project that is fully migrated (supabase link ...).
#   2. bash scripts/rebuild-snapshot.sh    (or: npm run db:rebuild-snapshot)
#
# Requires the Supabase CLI (the same tool run-fresh-environment-test.sh uses).

set -euo pipefail

OUT="supabase/rebuild/0000_full_rebuild.sql"
TMP="$(mktemp)"
EPI="$(mktemp)"
# The new snapshot is assembled in BUILD and only moved over OUT once it has been
# verified below. Writing OUT directly (as this script used to) meant a run that failed
# its checks still left the broken file on disk - strictly worse than the committed
# snapshot it replaced, and silently committed by anyone who did not read stderr.
# Guarded like 0051 guards pg_cron, so a bare local Postgres without the extension still
# provisions (minus the exclusion constraint) rather than aborting.
EXT_SQL=$(
  cat <<'EXTSQL'
do $$
begin
  create extension if not exists btree_gist with schema public;
exception when others then
  raise warning 'btree_gist could not be installed (%) - class_sessions_no_tutor_overlap will NOT be created, so this database can double-book a tutor.', sqlerrm;
end $$;
EXTSQL
)

BUILD="$(mktemp)"
trap 'rm -f "$TMP" "$EPI" "$BUILD"' EXIT

# TWO WAYS TO PRODUCE THE DUMP.
#
# 1. SNAPSHOT_DB_URL - dump straight from a fully-migrated database with the local pg_dump.
#    Use this when Docker is unavailable: `supabase db dump` shells out to pg_dump INSIDE A
#    CONTAINER, so it needs Docker even with its own --db-url, while pg_dump against a plain
#    Postgres needs nothing. The flags below are the equivalent of what the CLI runs, and the
#    verification block further down proves the artifact either way.
#    pg_dump must MATCH THE SERVER MAJOR VERSION, or it refuses (and a mismatch would in any
#    case churn the diff with unrelated formatting changes).
#      SNAPSHOT_DB_URL=postgresql://postgres@127.0.0.1:5432/certed_scratch bash scripts/rebuild-snapshot.sh
#
# 2. The Supabase CLI against the linked/local project (the original path).
if [ -n "${SNAPSHOT_DB_URL:-}" ]; then
  if ! command -v pg_dump >/dev/null 2>&1; then
    echo "Error: SNAPSHOT_DB_URL is set but pg_dump is not on PATH." >&2
    exit 1
  fi
  echo "Dumping the public schema from SNAPSHOT_DB_URL with $(pg_dump --version)..."
  # Schema only (roles + data excluded) - this is a provisioning snapshot, not a backup.
  # --no-owner: the snapshot must apply as whatever role provisions it.
  pg_dump --dbname="$SNAPSHOT_DB_URL" --schema=public --schema-only --no-owner -f "$TMP"
else
  if ! command -v supabase >/dev/null 2>&1; then
    echo "Error: the Supabase CLI is not on PATH (and SNAPSHOT_DB_URL is unset)." >&2
    echo "Either install it, or point SNAPSHOT_DB_URL at a fully-migrated database." >&2
    exit 1
  fi
  echo "Dumping the public schema from the linked database..."
  supabase db dump --schema public -f "$TMP"
fi

# Highest migration this snapshot reflects. Emitted as a machine-readable
# 0001..NNNN marker in the header so a freshness check (CI) can compare it to the
# migration chain and flag a stale snapshot. Keep the marker's format stable.
LATEST="$(ls supabase/migrations/*.sql | xargs -n1 basename | sed -E 's/_.*//' | sort | tail -1)"

# Table + FUNCTION privilege epilogue (R-01 / C-01). A schema-only dump keeps each table's column GRANTs
# but DROPS the migration chain's table-wide REVOKEs of Supabase's default grants (they
# were no-ops in the migrated-only dump source). Re-emit them - see the comment block
# below for why order and qualification are both load-bearing. This is injected BEFORE
# the ACL section (a table-level REVOKE cascades to that table's column privileges, so it
# MUST precede the column GRANTs or it wipes them). tests/unit/snapshot-privilege-epilogue
# asserts presence, public. qualification, and this ordering.
#
# THIS LIST IS HAND-MAINTAINED. Add an entry whenever a migration adds a table-level
# REVOKE, or a snapshot-provisioned database silently regains the grant the chain
# removed. tests/unit/snapshot-privilege-epilogue.test.ts compares this against every
# `revoke ... on table` in supabase/migrations and fails when one is missing, so the
# gap surfaces in CI rather than in a provisioned environment.
cat >"$EPI" <<'EPILOGUE'
--
-- Table privilege epilogue (R-01)
-- ============================================================================
-- The migration chain REVOKEs Supabase's table-wide default grants, then GRANTs back the
-- specific columns each role may touch. A schema-only dump keeps the column GRANTs but
-- drops the table-wide REVOKEs, so re-apply them HERE, BEFORE the ACL section, because:
--   1. ORDER - a table-level REVOKE cascades to that table's COLUMN privileges, so a
--      REVOKE after the column GRANTs wipes them (withdraw / self-service / session read
--      break). Revoking first, then letting the ACL GRANTs below re-establish the
--      columns, mirrors the chain (revoke in 0033, grant in 0064/0065).
--   2. QUALIFICATION - pg_dump empties search_path, so an unqualified name errors and
--      silently does nothing. Every name here is public.<table>.
-- ============================================================================
REVOKE INSERT, UPDATE ON TABLE public.submissions FROM authenticated;
REVOKE SELECT ON TABLE public.class_sessions FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.class_sessions FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.attendance FROM anon, authenticated;
REVOKE UPDATE ON TABLE public.notifications FROM anon, authenticated;
REVOKE UPDATE ON TABLE public.profiles FROM authenticated;
REVOKE ALL ON TABLE public.reminders FROM authenticated;
REVOKE ALL ON TABLE public.billing_rates FROM anon, authenticated;


EPILOGUE

{
  cat <<HEADER
-- ============================================================================
-- Cert-Ed Academia - full schema rebuild
-- ============================================================================
-- GENERATED by scripts/rebuild-snapshot.sh (supabase db dump) from the numbered
-- migrations (supabase/migrations/0001..${LATEST}) applied in order. The numbered
-- migrations are the single source of truth; this file provisions a fresh
-- database in one shot and is kept byte-identical to applying them in order.
-- DO NOT hand-edit - re-run the script instead.
--
-- Requires the Supabase-provided auth schema (auth.users, auth.uid()) and the
-- anon / authenticated / service_role roles, present on any Supabase project.
-- ============================================================================

HEADER
  # Splice the epilogue in immediately before the first ACL entry (pg_dump marks the
  # section with "; Type: ACL;"). One-line lookahead so it lands before that block's
  # opening "--" comment rather than inside it.
  EPI_TEXT="$(cat "$EPI")" EXT_TEXT="$EXT_SQL" awk '
    BEGIN {
      # ENVIRON is read verbatim - unlike -v, which applies escape processing and so
      # mangles any path containing backslashes. The epilogue TEXT is passed here rather
      # than a path to read, removing the failure mode entirely: there is nothing left to
      # open, so nothing that can silently fail and leave the dump unspliced.
      epi = ENVIRON["EPI_TEXT"]
      ext = ENVIRON["EXT_TEXT"]
      if (epi == "") { print "awk: the R-01 epilogue text is empty - refusing to splice nothing" > "/dev/stderr"; exit 1 }
      epi = epi "\n"
    }
    {
      if (!done && $0 ~ /; Type: ACL;/) { printf "%s", epi; done = 1 }
      # Extensions are FILTERED OUT of a --schema=public dump (they do not belong to the
      # schema), so anything the schema depends on must be re-declared. The 0101
      # class_sessions_no_tutor_overlap constraint is an EXCLUDE USING gist over (uuid,
      # tstzrange), needing btree_gist for the uuid operator class - without it the snapshot
      # apply at all. Emitted right after the CREATE SCHEMA that pg_dump itself writes (the
      # schema must exist first, and creating it here would collide with that statement),
      # and well before the constraint that needs it.
      if (!extDone && $0 ~ /^CREATE SCHEMA public;/) { print; print ""; print ext; extDone = 1; next }
      if (havePrev) print prev
      prev = $0; havePrev = 1
    }
    END { if (havePrev) print prev }
  ' "$TMP"
} >"$BUILD"

# Singleton data epilogue. `supabase db dump --schema public` is SCHEMA-only, so it drops
# the one row 0001 inserts into org_settings - and that row is not optional: it is the
# institute name/timezone/currency/bank details every branded document reads, and
# selectOrgSettings() fetches it with .single(), which ERRORS on zero rows. Without this,
# a snapshot-provisioned database 500s the calendar feed, receipts, pay slips, report
# cards and the portal footer until someone inserts the row by hand. Appended AFTER the
# ACL section so the table exists (and its grants are settled) before the insert.
# Idempotent, so re-running the snapshot over a provisioned database is a no-op.
# tests/unit/snapshot-singleton-seed.test.ts asserts this block survives regeneration.

cat >>"$BUILD" <<'SEED'

--
-- Singleton data epilogue
-- ============================================================================
-- org_settings holds exactly one row (its `id boolean primary key default true` +
-- org_settings_single_row check enforce that). Migration 0001 inserts it; a schema-only
-- dump cannot carry it, so re-create it here. Column defaults supply the institute name,
-- contact details, timezone, currency and document prefixes - an admin edits the rest in
-- Settings. Without this row every org_settings read fails with PGRST116.
-- ============================================================================
INSERT INTO public.org_settings (id) VALUES (true) ON CONFLICT DO NOTHING;
SEED

cat >>"$BUILD" <<'FUNCEPI'
--
-- Function privilege epilogue (C-01)
-- ============================================================================
-- The same problem as the tables above, one object class over, and it was missed
-- because both this epilogue and its CI gate only ever looked at TABLES.
--
-- pg_dump writes function ACLs relative to POSTGRES defaults (EXECUTE to PUBLIC), so it
-- emits `REVOKE ALL ON FUNCTION x FROM PUBLIC`. A real Supabase project ALSO grants
-- EXECUTE to anon and authenticated as NAMED roles via default privileges, and revoking
-- from PUBLIC does not remove a named-role grant. So a snapshot-provisioned database
-- silently hands every SECURITY DEFINER function to the publishable key - including
-- issue_receipt_doc / issue_payslip_doc, which do not self-authorize (C-01), plus
-- revoke_profile_guarded, claim_pending_emails and next_document_number.
--
-- Deny by default, allow by name - the same sweep migration 0096 runs, so a
-- chain-provisioned and a snapshot-provisioned database end up identical. Placed BEFORE
-- the ACL section so the GRANTs pg_dump emits below still apply.
-- ============================================================================
DO $EPI$
DECLARE
  fn record;
  keeps_authenticated CONSTANT text[] := ARRAY[
    'current_app_role', 'current_profile_id', 'current_status',
    'finance_totals', 'finance_totals_base',
    'is_active_admin', 'is_active_sub_admin', 'is_conversation_member',
    'is_app_link', 'is_enrolled', 'is_http_link', 'is_self_active',
    'mentors_class', 'mentors_student', 'replace_own_submission',
    'teaches_class', 'teaches_class_write',
    'user_has_persona', 'user_is_admin', 'user_is_mentor_for_student'
  ];
BEGIN
  FOR fn IN
    SELECT p.oid::regprocedure AS sig, p.proname AS name
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND NOT EXISTS (
        SELECT 1 FROM pg_depend d
        WHERE d.objid = p.oid AND d.classid = 'pg_proc'::regclass AND d.deptype = 'e'
      )
  LOOP
    EXECUTE format('revoke execute on function %s from public, anon, authenticated', fn.sig);
    IF fn.name = ANY (keeps_authenticated) THEN
      EXECUTE format('grant execute on function %s to authenticated', fn.sig);
    ELSE
      EXECUTE format('grant execute on function %s to service_role', fn.sig);
    END IF;
  END LOOP;
END
$EPI$;

ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM public, anon, authenticated;
FUNCEPI

# ── Verify the BUILT ARTIFACT, not the ingredients ────────────────────────────
# The old check asked whether the DUMP had an ACL section. That is the wrong question:
# the dump can be perfect while the splice still produces nothing (see the awk guard
# above), and a snapshot missing its epilogue passes every other gate - the unit test
# only compares this script's list against the migrations, and privilege parity can
# agree for unrelated reasons. So assert on what will actually be committed.
fail() { echo "::error::rebuild-snapshot: $1" >&2; echo "Kept the existing $OUT unchanged." >&2; exit 1; }

grep -q '; Type: ACL;' "$TMP" || fail "no ACL section in the dump - nothing to splice the R-01 epilogue before."

# Every REVOKE this script intends to emit must be in the output, verbatim.
missing=0
while IFS= read -r line; do
  [ -z "$line" ] && continue
  grep -Fqx "$line" "$BUILD" || { echo "  missing: $line" >&2; missing=1; }
done < <(grep '^REVOKE' "$EPI")
[ "$missing" -eq 0 ] || fail "the table privilege epilogue (R-01) did not reach the snapshot."

# The table REVOKEs must precede the first ACL entry: a table-level REVOKE cascades to
# that table's COLUMN privileges, so landing after the column GRANTs wipes them.
first_revoke=$(grep -n '^REVOKE .* ON TABLE public\.' "$BUILD" | head -1 | cut -d: -f1)
first_acl=$(grep -n '; Type: ACL;' "$BUILD" | head -1 | cut -d: -f1)
[ -n "$first_revoke" ] && [ -n "$first_acl" ] && [ "$first_revoke" -lt "$first_acl" ]   || fail "the table privilege epilogue is not before the first ACL entry (revoke=$first_revoke acl=$first_acl)."

grep -Fq 'create extension if not exists btree_gist' "$BUILD" \
  || fail "the extension prologue did not reach the snapshot - it would fail to apply."
# The two appended epilogues must be present too.
grep -Fq 'INSERT INTO public.org_settings (id) VALUES (true)' "$BUILD"   || fail "the org_settings singleton seed did not reach the snapshot."
grep -Fq 'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS' "$BUILD"   || fail "the function privilege epilogue (C-01) did not reach the snapshot."

# Make the artifact REPRODUCIBLE. pg_dump 18 wraps the dump in `\restrict <token>` /
# `\unrestrict <token>`, where the token is random per run. It stops psql executing
# anything embedded in the dump before the wrapper closes - worth keeping - but a fresh
# random value on every run meant regenerating an UNCHANGED schema still produced a diff.
# That is corrosive for a committed artifact: a reviewer cannot tell "the schema moved"
# from "someone re-ran the script", so the noise trains people to skim the one diff that
# most needs reading.
#
# Pinning the token keeps the guarantee, because the guarantee is that the token does not
# appear in the body - which is asserted here rather than assumed. If it ever did collide,
# this fails loudly instead of emitting a dump psql could be tricked out of.
RESTRICT_TOKEN="certed_rebuild_snapshot_restrict"
if grep -Fq "$RESTRICT_TOKEN" <(grep -vE '^\\(un)?restrict ' "$BUILD"); then
  fail "the pinned \\restrict token appears in the dump body - pick a different RESTRICT_TOKEN."
fi
if grep -qE '^\\restrict ' "$BUILD"; then
  sed -i -E "s/^\\\\restrict .*/\\\\restrict ${RESTRICT_TOKEN}/; s/^\\\\unrestrict .*/\\\\unrestrict ${RESTRICT_TOKEN}/" "$BUILD"
  grep -qE "^\\\\unrestrict ${RESTRICT_TOKEN}$" "$BUILD" \
    || fail "pinned the \\restrict token but the matching \\unrestrict did not update - the dump would not parse."
fi

# Verified - only now does it replace the committed snapshot.
mv "$BUILD" "$OUT"

echo "Wrote $OUT"
echo "Review the diff (git diff $OUT) and commit alongside the migrations it reflects."
