#!/bin/bash

# Regenerate supabase/rebuild/0000_full_rebuild.sql from a FULLY-MIGRATED database.
#
# The rebuild snapshot is a pg_dump of the end state - it provisions a fresh DB in
# one shot. It MUST be regenerated by dumping, never hand-edited: hand-edits have
# silently drifted it before (a stale mentorships.tutor_id, a divergent persona
# scheme, a duplicate constraint that made it fail to apply at all). Run this after
# adding migrations so the one-shot file stays byte-accurate to the chain.
#
# Usage:
#   1. Point the Supabase CLI at a database that has the ENTIRE migration chain
#      applied. The simplest is a fresh local db:
#        supabase db reset      # drops + replays supabase/migrations/*.sql
#      Or link to a remote project that is fully migrated (supabase link ...).
#   2. bash scripts/rebuild-snapshot.sh    (or: npm run db:rebuild-snapshot)
#
# Requires the Supabase CLI (the same tool run-fresh-environment-test.sh uses).

set -euo pipefail

OUT="supabase/rebuild/0000_full_rebuild.sql"
TMP="$(mktemp)"
EPI="$(mktemp)"
trap 'rm -f "$TMP" "$EPI"' EXIT

if ! command -v supabase >/dev/null 2>&1; then
  echo "Error: the Supabase CLI is not on PATH. Install it, then re-run." >&2
  exit 1
fi

echo "Dumping the public schema from the linked database..."
# Schema only (roles + data excluded) - this is a provisioning snapshot, not a backup.
supabase db dump --schema public -f "$TMP"

# Highest migration this snapshot reflects. Emitted as a machine-readable
# 0001..NNNN marker in the header so a freshness check (CI) can compare it to the
# migration chain and flag a stale snapshot. Keep the marker's format stable.
LATEST="$(ls supabase/migrations/*.sql | xargs -n1 basename | sed -E 's/_.*//' | sort | tail -1)"

# Table privilege epilogue (R-01). A schema-only dump keeps each table's column GRANTs
# but DROPS the migration chain's table-wide REVOKEs of Supabase's default grants (they
# were no-ops in the migrated-only dump source). Re-emit them - see the comment block
# below for why order and qualification are both load-bearing. This is injected BEFORE
# the ACL section (a table-level REVOKE cascades to that table's column privileges, so it
# MUST precede the column GRANTs or it wipes them). tests/unit/snapshot-privilege-epilogue
# asserts presence, public. qualification, and this ordering.
cat >"$EPI" <<'EPILOGUE'
--
-- Table privilege epilogue (R-01)
-- ============================================================================
-- The migration chain REVOKEs Supabase's table-wide default grants, then GRANTs back the
-- specific columns each role may touch. A schema-only dump keeps the column GRANTs but
-- drops the table-wide REVOKEs, so re-apply them HERE, BEFORE the ACL section, because:
--   1. ORDER - a table-level REVOKE cascades to that table's COLUMN privileges, so a
--      REVOKE after the column GRANTs wipes them (withdraw / self-service / session read
--      break). Revoking first, then letting the ACL GRANTs below re-establish the
--      columns, mirrors the chain (revoke in 0033, grant in 0064/0065).
--   2. QUALIFICATION - pg_dump empties search_path, so an unqualified name errors and
--      silently does nothing. Every name here is public.<table>.
-- ============================================================================
REVOKE INSERT, UPDATE ON TABLE public.submissions FROM authenticated;
REVOKE SELECT ON TABLE public.class_sessions FROM authenticated;
REVOKE UPDATE ON TABLE public.notifications FROM anon, authenticated;
REVOKE UPDATE ON TABLE public.profiles FROM authenticated;
REVOKE ALL ON TABLE public.reminders FROM authenticated;

EPILOGUE

{
  cat <<HEADER
-- ============================================================================
-- Cert-Ed Academia - full schema rebuild
-- ============================================================================
-- GENERATED by scripts/rebuild-snapshot.sh (supabase db dump) from the numbered
-- migrations (supabase/migrations/0001..${LATEST}) applied in order. The numbered
-- migrations are the single source of truth; this file provisions a fresh
-- database in one shot and is kept byte-identical to applying them in order.
-- DO NOT hand-edit - re-run the script instead.
--
-- Requires the Supabase-provided auth schema (auth.users, auth.uid()) and the
-- anon / authenticated / service_role roles, present on any Supabase project.
-- ============================================================================

HEADER
  # Splice the epilogue in immediately before the first ACL entry (pg_dump marks the
  # section with "; Type: ACL;"). One-line lookahead so it lands before that block's
  # opening "--" comment rather than inside it.
  awk -v epifile="$EPI" '
    BEGIN { while ((getline l < epifile) > 0) epi = epi l "\n" }
    {
      if (!done && $0 ~ /; Type: ACL;/) { printf "%s", epi; done = 1 }
      if (havePrev) print prev
      prev = $0; havePrev = 1
    }
    END { if (havePrev) print prev }
  ' "$TMP"
} >"$OUT"

if ! grep -q '; Type: ACL;' "$TMP"; then
  echo "Error: no ACL section found in the dump - the R-01 epilogue was NOT spliced in." >&2
  echo "The rebuild snapshot would provision a DB that regains the revoked table grants." >&2
  exit 1
fi

echo "Wrote $OUT"
echo "Review the diff (git diff $OUT) and commit alongside the migrations it reflects."
